export const FETCH_LOGIN_INFO = 'FETCH_LOGIN_INFO';
export const FETCH_MY_MUSIC_LIST_INFO = 'FETCH_MY_MUSIC_LIST_INFO';
export const FETCH_RECOMMEND_LIST_INFO = 'FETCH_RECOMMEND_LIST_INFO';

export const DELETE_MUSIC = 'DELETE_MUSIC';
export const RENAME_MUSIC = 'RENAME_MUSIC';
export const CUT_MUSIC = 'CUT_MUSIC';
export const STORE_SELECTED_MUSIC = 'STORE_SELECTED_MUSIC';
